name: OpenFastTrace Requirement Tracing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  trace:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run OpenFastTrace
      run: |
        java -jar openfasttrace.jar trace --report-verbosity minimal .
    
    - name: Generate HTML Report
      run: |
        java -jar openfasttrace.jar trace -o html -f trace-report.html .
    
    - name: Upload HTML Report as Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: oft-trace-report
        path: trace-report.html
        retention-days: 30 