name: OpenFastTrace Requirement Tracing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  trace:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    
    - name: Set up JDK 17
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run OpenFastTrace
      run: |
        java -jar openfasttrace.jar trace --report-verbosity minimal SimpleRequirement.md SimpleHello.java SimpleHelloTest.java
    
    - name: Generate HTML Report
      run: |
        java -jar openfasttrace.jar trace -o html -f trace-report.html SimpleRequirement.md SimpleHello.java SimpleHelloTest.java
    
    - name: Upload HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: oft-trace-report
        path: trace-report.html
        retention-days: 30 